<a href="https://colab.research.google.com/github/amanprasad625566-design/ybi_foundation_internship/blob/main/ybifoundation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.13/dist-packages (2.2.3)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.13/dist-packages (from pandas) (2.1.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.13/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.13/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.13/dist-packages (from pandas) (2026.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.13/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [7]:
import pandas as pd

In [8]:
data = ({
    "Name": ["Aman", "Rahul", "Riya", "Priya", "Rohit"],
    "Age": [20, 21, 19, 20, 22],
    "Marks": [85, 72, 90, 68, 78]
})

df = pd.DataFrame(data)

df

    Name  Age  Marks
0   Aman   20     85
1  Rahul   21     72
2   Riya   19     90
3  Priya   20     68
4  Rohit   22     78

In [9]:
df.shape

(5, 3)

In [10]:
df.columns

Index(['Name', 'Age', 'Marks'], dtype='object')

In [11]:
df.head()

    Name  Age  Marks
0   Aman   20     85
1  Rahul   21     72
2   Riya   19     90
3  Priya   20     68
4  Rohit   22     78

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    5 non-null      object
 1   Age     5 non-null      int64
 2   Marks   5 non-null      int64
dtypes: int64(2), object(1)
memory usage: 252.0+ bytes

In [13]:
df

    Name  Age  Marks
0   Aman   20     85
1  Rahul   21     72
2   Riya   19     90
3  Priya   20     68
4  Rohit   22     78

In [14]:
df.head(3)

    Name  Age  Marks
0   Aman   20     85
1  Rahul   21     72
2   Riya   19     90

In [15]:
df.tail(2)

    Name  Age  Marks
3  Priya   20     68
4  Rohit   22     78

In [16]:
df.columns

Index(['Name', 'Age', 'Marks'], dtype='object')

In [18]:
df["Name"]

0     Aman
1    Rahul
2     Riya
3    Priya
4    Rohit
Name: Name, dtype: object

In [19]:
df["Marks"]

0    85
1    72
2    90
3    68
4    78
Name: Marks, dtype: int64

In [20]:
df[["Name", "Marks"]]

    Name  Marks
0   Aman     85
1  Rahul     72
2   Riya     90
3  Priya     68
4  Rohit     78

In [21]:
df.describe()

             Age      Marks
count   5.000000   5.000000
mean   20.400000  78.600000
std     1.140175   9.044335
min    19.000000  68.000000
25%    20.000000  72.000000
50%    20.000000  78.000000
75%    21.000000  85.000000
max    22.000000  90.000000

In [22]:
df["Marks"].mean()

np.float64(78.6)

In [23]:
df["Marks"].max()

90

In [24]:
df["Marks"].min()

68

In [25]:
df[df["Marks"] > 80]

   Name  Age  Marks
0  Aman   20     85
2  Riya   19     90

In [26]:
df[df["Age"] >= 20]

    Name  Age  Marks
0   Aman   20     85
1  Rahul   21     72
3  Priya   20     68
4  Rohit   22     78

In [27]:
df.sort_values("Marks")

    Name  Age  Marks
3  Priya   20     68
1  Rahul   21     72
4  Rohit   22     78
0   Aman   20     85
2   Riya   19     90

In [28]:
df.sort_values("Marks", ascending=False)

    Name  Age  Marks
2   Riya   19     90
0   Aman   20     85
4  Rohit   22     78
1  Rahul   21     72
3  Priya   20     68

In [29]:
df.loc[df["Marks"].idxmax()]

Name     Riya
Age        19
Marks      90
Name: 2, dtype: object

In [30]:
df.loc[df["Marks"].idxmin()]

Name     Priya
Age         20
Marks       68
Name: 3, dtype: object

In [31]:
df[df["Marks"] > df["Marks"].mean()]

   Name  Age  Marks
0  Aman   20     85
2  Riya   19     90